### List Expenses
GET http://localhost:3000/expenses
### List Expenses filter by date
GET http://localhost:3000/expenses?month=04&year=2025

### Create Expense
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "title": "Restaurante",
  "amount": 100.00,
  "category": "Lazer",
  "date": "2025-04-26T20:30:00.000Z"
}

### Get Expense by ID
GET http://localhost:3000/expenses/0fa1b274-7aa1-4ec7-a73b-58aa6bd0c06d

### Update Expense by ID
PATCH http://localhost:3000/expenses/a4cc8c36-e544-4017-8c53-e7a96ea91e0e
Content-Type: application/json

{
  "amount": 301.00
}

### Delete Expense by ID
DELETE http://localhost:3000/expenses/af5335d8-6c28-406d-ac17-3a1749ee11ba
